title: Guo Zhengjin's Blog
author: Guo Zhengjin
# email: guo.zhengjin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A software developer's technical blog. #Python #CSharp #DataScience #MachineLearning #Visualization

# social links
#twitter_username: liudongqiang # DO NOT include the @ character, or else the build will fail!
github_username: kokuraxc # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

minima:
  skin: dark

plugins:
  - jekyll-feed
  - jekyll-seo-tag
